from airflow import DAG
from airflow.providers.http.operators.http import HttpOperator
from airflow.decorators import task
from airflow.providers.postgres.hooks.postgres import PostgresHook
import pendulum

## Define the DAG
with DAG(
    dag_id='nasa_apod_postgres_etl',
    start_date=pendulum.datetime(2024, 1, 1, tz='UTC'),
    schedule='@daily',
    catchup=False
) as dag : 
    ## Step 1: Create the table if it doesn't exist
    @task
    def create_table() :
        # Hooks in Airflow are interfaces to interact with external systems. 
        # They provide a way to connect to databases, APIs, and other services 
        # without having to write custom code for each connection. 
        # The PostgresHook is a specific hook designed to interact with PostgreSQL databases. 
        # It allows you to execute SQL commands, run queries, and manage database connections in a more streamlined way within your Airflow tasks.
        ### initialize the Postgres hook
        pg_hook = PostgresHook(postgres_conn_id='my_postgres_conn')

        ### SQL command to create the table
        create_table_query = """
            CREATE TABLE IF NOT EXISTS nasa_apod (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255),
                explanation TEXT,
                url TEXT,
                date DATE UNIQUE,
                media_type VARCHAR(50)
            );
        """

        ### Execute the SQL command
        pg_hook.run(create_table_query)


    ## Step 2: Fetch the APOD data from NASA API [Extract Pipeline]
    extract_apod = HttpOperator(
        task_id='extract_apod',
        method='GET',
        http_conn_id='nasa_api_conn', # Connection ID defined in Airflow Connections
        endpoint='planetary/apod', # NASA APOD API endpoint
        data={"api_key": "{{ conn.api_key.password }}"},  # Pass the API key as a parameter
        response_filter=lambda response: response.json()  # Parse the JSON response
    )
    
    ## Step 3: Transform the data (Pick the information that i need to save) [Transform Pipeline]
    @task
    def transform_data(apod_data) :
        # Extract relevant fields from the API response
        transformed_data = {
            'title': apod_data.get('title' , ''),
            'explanation': apod_data.get('explanation' , ''),
            'url': apod_data.get('url' , ''),
            'date': apod_data.get('date' , ''),
            'media_type': apod_data.get('media_type' , '')
        }
        return transformed_data

    ## Step 4: Load the data into Postgres [Load Pipeline]
    @task
    def load_data(transformed_data) :
        pg_hook = PostgresHook(postgres_conn_id='my_postgres_conn')
        insert_sql = """
            INSERT INTO nasa_apod (title, explanation, url, date, media_type)
            VALUES (%s, %s, %s, %s, %s)
        """
        pg_hook.run(insert_sql, parameters=(
            transformed_data['title'],
            transformed_data['explanation'],
            transformed_data['url'],
            transformed_data['date'],
            transformed_data['media_type']
        ))


    ## Step 5: Verify the data DBViewer


    ## Step 6: Task dependencies
    create_table() >> extract_apod ## Ensure the table is created before fetching data
    api_response = extract_apod.output ## Store the API response for transformation
    transformed_data = transform_data(api_response) ## Transform the data after extraction
    load_data(transformed_data) ## Load the transformed data into Postgres
